FIND_PATH(SKYPE_INCLUDE_DIR skype.h /usr/include/skype /usr/local/include/skype)

FIND_LIBRARY(SKYPE_LIBRARY NAMES skype PATH /usr/lib /usr/local/lib) 

IF (SKYPE_INCLUDE_DIR AND SKYPE_LIBRARY)
   SET(SKYPE_FOUND TRUE)
ENDIF (SKYPE_INCLUDE_DIR AND SKYPE_LIBRARY)


IF (SKYPE_FOUND)
   IF (NOT SKYPE_FIND_QUIETLY)
      MESSAGE(STATUS "Found libskype: ${SKYPE_LIBRARY}")
   ENDIF (NOT SKYPE_FIND_QUIETLY)
ELSE (SKYPE_FOUND)
   IF (SKYPE_FIND_REQUIRED)
      MESSAGE(FATAL_ERROR "Could not find libskype")
   ENDIF (SKYPE_FIND_REQUIRED)
ENDIF (SKYPE_FOUND)

