FIND_PATH(EVENTSIMULATION_INCLUDE_DIR eventhandler.h /usr/include/simon/eventsimulation /usr/local/include/simon/eventsimulation)

FIND_LIBRARY(EVENTSIMULATION_LIBRARY NAMES eventsimulation PATH /usr/lib /usr/local/lib) 

IF (EVENTSIMULATION_INCLUDE_DIR AND EVENTSIMULATION_LIBRARY)
   SET(EVENTSIMULATION_FOUND TRUE)
ENDIF (EVENTSIMULATION_INCLUDE_DIR AND EVENTSIMULATION_LIBRARY)


IF (EVENTSIMULATION_FOUND)
   IF (NOT EVENTSIMULATION_FIND_QUIETLY)
      MESSAGE(STATUS "Found eventsimulation: ${EVENTSIMULATION_LIBRARY}")
   ENDIF (NOT EVENTSIMULATION_FIND_QUIETLY)
ELSE (EVENTSIMULATION_FOUND)
   IF (EVENTSIMULATION_FIND_REQUIRED)
      MESSAGE(FATAL_ERROR "Could not find eventsimulation")
   ENDIF (EVENTSIMULATION_FIND_REQUIRED)
ENDIF (EVENTSIMULATION_FOUND)

